project:
  type: book
  output-dir: docs

book:
  title: "Data Science Course Notes"
  author: "Hung Tong"
  date: "February 2026"
  chapters:
    - index.qmd
    # - intro.qmd
    
    - part: "Base R programming"
      chapters:
          - ls1_basics.qmd
          - ls2a_vector.qmd
          - ls2b_vector.qmd
          - ls2c_vector.qmd
          - ls3a_data_frame.qmd
        
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

number-sections: false

format:
  html:
    theme: cosmo
    toc: true
    self-contained: true
  pdf:
    documentclass: scrreprt



